name: Update Organization Stats

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update README with Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BurkimbIA
          template: classic
          base: header, activity, community, repositories
          config_timezone: Africa/Ouagadougou
          plugin_repositories: yes
          plugin_repositories_featured: BurkimbIA/burkimbia
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          output_action: commit
          committer_branch: main
          committer_message: "Update organization stats"
