name: Update Organization Stats

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write   # needed only to push svg

concurrency:
  group: metrics-stats
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Generate metrics (no auto commit)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BurkimbIA
          template: classic
          base: header, activity, community, repositories
          config_timezone: Africa/Ouagadougou
          plugin_repositories: yes
          plugin_repositories_featured: BurkimbIA/burkimbia
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          output_action: none
          filename: github-metrics.svg

      - name: Detect changes
        id: diff
        run: |
          if git diff --quiet -- github-metrics.svg 2>/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated metrics
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-metrics.svg
          git commit -m "chore(metrics): update metrics svg"
          git push

      - name: Skip commit (no changes)
        if: steps.diff.outputs.changed != 'true'
        run: echo "No metrics changes detected, skipping commit."
