name: Update Organization Stats

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write   # needed only to push svg

concurrency:
  group: metrics-stats
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Generate metrics (no auto commit)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BurkimbIA
          template: classic
          base: header, activity, community, repositories
          config_timezone: Africa/Ouagadougou
          plugin_repositories: yes
          plugin_repositories_featured: BurkimbIA/burkimbia
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          output_action: none
          filename: metrics_renders/github-metrics.svg

      - name: Compute total organization stars
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          echo "Fetching repositories for organization BurkimbIA"
          page=1
          total=0
          tmpfile=$(mktemp)
          while : ; do
            resp=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/orgs/BurkimbIA/repos?type=public&per_page=100&page=$page")
            count=$(echo "$resp" | jq 'length')
            if [ "$count" -eq 0 ]; then
              break
            fi
            stars=$(echo "$resp" | jq '[.[] | select(.fork==false) | .stargazers_count] | add // 0')
            total=$((total + stars))
            page=$((page + 1))
          done
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          mkdir -p metrics_renders
            cat > metrics_renders/org-stars.json <<EOF
          {
            "organization": "BurkimbIA",
            "total_stars": $total,
            "updated_at": "$timestamp"
          }
          EOF
          echo "Computed total stars: $total"

      - name: Commit metrics (always)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metrics_renders/github-metrics.svg metrics_renders/org-stars.json
          git commit -m "chore(metrics): refresh metrics svg + stars" || echo "No changes to commit"
          git push || echo "Nothing pushed"
